MCU = AIR32F103
MCU_LDSCRIPT = AIR32F103xCuf2
FIRMWARE_FORMAT = uf2

BOOTLOADER = custom

EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = embedded_flash

LTO_ENABLE = yes

KEYBOARD_SHARED_EP = yes
WS2812_DRIVER = pwm

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
SRC += uf2_boot.c


