#pragma once
#include "config_common.h"

/* USB Device descriptor parameter */
#define VENDOR_ID       0xFEED
#define PRODUCT_ID      0x6003
#define DEVICE_VER      0x0001
#define MANUFACTURER    JL-K26E6
#define PRODUCT         JL-K26E6

#define MIDI_ADVANCED

 /* 层指示灯 */
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#define RGBLIGHT_LAYER_BLINK

#define MATRIX_ROWS 7
#define MATRIX_COLS 7

#define MATRIX_ROW_PINS {  B13,B15,A10,B4,B6,B8,A15}
#define MATRIX_COL_PINS {  B12,B14,A8,B3,B5,B7,C15}
#define UNUSED_PINS

#define DIODE_DIRECTION COL2ROW

#define DEBOUNCE 5

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE

#define QMK_KEYS_PER_SCAN 12
#define FORCE_NKRO



#ifdef ENCODER_ENABLE
#define ENCODERS_PAD_A { B10, B1 , A7, A5, A3, A1 }
#define ENCODERS_PAD_B { C14, B0 , A6, A4, A2, A0 }

#define ENCODER_RESOLUTION 4
#ifdef ENCODER_TRIGGER_ENABLE
#define ENCODER_PAD_A_KEY_POS {6, 1},{6, 3},{6, 5},{2, 6},{4, 6},{6, 6}
#define ENCODER_PAD_B_KEY_POS {6, 0},{6, 2},{6, 4},{1, 6},{3, 6},{5, 6}
#endif
#endif



#ifdef RADIAL_CONTROLLER_ENABLE
#define RADIAL_CONTROLLER_RESOLUTION 100
#define RADIAL_CONTROLLER_ROTATION_STEP 10
#define RADIAL_CONTROLLER_TIMER_DELAY 15
#define RADIAL_CONTROLLER_ROTATION_CONTINUE_BUTTON_ENABLE
#endif

#define RGB_DI_PIN B9
#ifdef RGB_DI_PIN 
#define RGBLIGHT_ANIMATIONS
#define RGBLED_NUM 4
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#endif

