MCU = STM32F103

# BOOTLOADER = stm32duino
BOOTLOADER = tinyuf2
ifeq ($(strip $(BOOTLOADER)), tinyuf2)
    MCU_LDSCRIPT = STM32F103x8_uf2
    FIRMWARE_FORMAT = uf2
	BOARD = STM32_F103_STM32DUINO
endif
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE

KEYBOARD_SHARED_EP = yes
# WS2812_DRIVER = pwm
CONSOLE_ENABLE = yes
