

ENCODER_ENABLE = yes
ENCODER_TRIGGER_ENABLE = yes
ALT_TAB_MARCO_ENABLE = yes
RADIAL_CONTROLLER_ENABLE = yes


VIA_ENABLE = yes
VIA_CUSTOM_KEYCODE_ENABLE = yes
ENCODER_TRIGGER_ENABLE = yes
# RGBLIGHT_ENABLE ?= yes
